name: CI
on: [workflow_dispatch]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i @lhci/cli
      - run: npm run build
      - run: lhci autorun
