name: Lighthouse CI
on:
  workflow_dispatch:


jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://www.sciencedirect.com
            https://www.elsevier.cn
            https://www.google.com
          budgetPath: ./budget.json # test performance budgets
          configPath: './lighthouserc.json' # custom Lighthouse configuration
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: false # upload lighthouse report to the temporary storage
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }} # LHCI server base URL
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }} # LHCI server token