name: sitespeed.io
on:
    workflow_dispatch:
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
    - name: code checkout
      uses: actions/checkout@v4
    - name: running sitespeed.io container with arguments and optional Docker options
      run: docker run -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:33.6.0 https://www.sitespeed.io --budget.configPath .github/budget.json -n 1 