name: speedcurve CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: speedcurve
    steps:
      - uses: actions/checkout@v4
    
      - uses: SpeedCurve-Metrics/speedcurve-test-action@v1.2.2
        with:
          api_key: ${{ secrets.SPEEDCURVE_API_KEY }}
          site_id:
            786274 # URL IDs can be retrieved from the /v1/sites API endpoint,
            # or by running the list-sites command with speedcurve-cli.